apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 3 # number of pods to run at any given time 
  selector:
    matchLabels:
      app: django-app # label used to identify pod 
      tier: frontend # label used to identify pod 
      track: stable # label used to identify pod 
  template:
    metadata:
      labels:
        app: django-app # label used to identify pod 
        tier: frontend # label used to identify pod 
        track: stable # label used to identify pod 
    spec:
      containers:
        - name : django-app-container # container name 
          image : maiempire/django_project-app # docker image of your django app 
          ports :
            - containerPort : 8000 # port exposed by your django app 
          env :
            - name : DATABASE_HOST # environment variable for database host 
              value : postgres # value of database host (same as service name)  
            - name : DATABASE_USER # environment variable for database user  
              valueFrom :
                secretKeyRef :
                  name : postgres # secret containing database credentials  
                  key : username  
            - name : DATABASE_PASSWORD # environment variable for database password  
              valueFrom :
                secretKeyRef :
                  name : postgres # secret containing database credentials  
                  key : password  