---
# tasks file for alert-manager

- name: Get the latest Alert Manager binaries
  shell: wget https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz

- name: Then extract the tarball
  command: tar xvfz alertmanager-0.25.0.linux-amd64.tar.gz

- name: Copy the files to their destinations
  shell: |
    cp alertmanager-0.25.0.linux-amd64/alertmanager /usr/local/bin
    cp alertmanager-0.25.0.linux-amd64/amtool /usr/local/bin/ 

- name: Create library folder
  command: mkdir /var/lib/alertmanager

- name: Remove the tarball
  shell: rm -rf alertmanager*

- name: Create Alert Manager configuration file
  copy: 
    src: alertmanager.yml
    dest: /etc/prometheus/alertmanager.yml

- name: Create systemd services for Prometheus and Node Exporter
  copy: 
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: Create alerting rules file
  copy: 
    src: rules.yml
    dest: /etc/prometheus/rules.yml

- name: Update the permissions for application files
  shell: chown -R prometheus:prometheus /etc/prometheus

- name: Start alertmanager service
  service:
    name: alertmanager
    state: restarted
    enabled: yes
    
- name: Restart prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: yes



