version: "3"

services:
  app:
    environment:
      APP_URL: "https://8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: .
    ports:
      - "8000:8080"
    volumes:
      - .:/django
    networks: 
      - app_network
  db:
    image: postgres:13
    restart: always
    environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"

    volumes: 
      - db:/var/lib/postgresql/data
    networks: 
      - app_network

networks:
  app_network:
    driver: bridge
    name: django-framwork

volumes:
  db:
    driver: local